<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLkAQ4va\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLkAQ4va/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLkAQ4va.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLkAQ4va\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLkAQ4va\App_KernelDevDebugContainer([
    'container.build_hash' => 'LkAQ4va',
    'container.build_id' => '65b33b92',
    'container.build_time' => 1670889330,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLkAQ4va');
